### ISSUE TITLE
browser scrolling to fast

### ISSUE THREAD

**Issue by mamema** [sirjmann92/nicotineplus-proper#10]
topic in question says it all.

scroll something like file list for example is too fast. Is this something which can be slowed down with some parameters?

**Comment by sirjmann92** [comment]
Check your browser, OS, and mouse settings and your reverse proxy websocket buffer settings. I tested with Opera, Chrome, Firefox, and Edge in both Windows and Linux (Ubunut) and ALL of them scroll both settings/file lists and search results at the default of 3 lines per scroll.

I don't believe this is an issue with the container image and there's no straightforward way for me to change it.

WebSocket Optimization: Since the Broadway backend uses WebSockets for communication, adjusting the WebSocket buffering and frequency in the client code or proxy server could make scrolling more manageable. If you're using a reverse proxy, setting a lower buffer size or increasing WebSocket frame interval could help smooth the experience.

I have this in my reverse proxy, but I'm not sure it makes a difference for scroll speed:
```
proxy_buffers 8 16k;
proxy_buffer_size 32k;
```

I'm going to close this issue, but if others start to complain then I'll dig into some potential options or workarounds from the image build side.
