### ISSUE TITLE
soulseek client port not reachable

### ISSUE THREAD

**Issue by mamema** [sirjmann92/nicotineplus-proper#8]
in the description there is no soulseek client port mentioned. The container is not reachable from outside from other soulseek members.
As i'm using also the full soulseekqt client with working port forwarding. This isn't a router issue

what i did without success:
1.) map additional ports inside the container eg 56347-56348
2.) installed curl within the container, excecuted curl http://www.slsknet.org/porttest.php?port=56348
         - port CLOSED
3.) modified the dockerfile an inserted additional EXPOSE ports. Made docker build. Did 2.) again, but same result

So even though the container can download stuff and search, because of not exposed client ports, the results are not the same as with exposed ports.....

**Comment by sirjmann92** [comment]
You don't need a soulseek CLIENT port exposed externally. You need a Nicotine+ LISTEN port exposed externally.

I haven't called out the soulseek SERVER port in my instructions but I do have it exposed in my personal setup (using a VPN container). The default soulseek port is 2242. You can map port 2242 in your container but you shouldn't need to expose it externally, and I'm not 100% convinced this is even needed, but since it's only exposed locally (mapped from host to container), there's little harm in leaving it mapped.

There are three ports in play, but (in my experience) only one of them needs to be exposed externally. That would be the Nicotine+ "listen" port.

e.g.
```
ports:
  - 2242:2242 #Soulseek server port, may not be needed
  - 6565:6565 #WebUI
  - xxxxx:xxxxx #Your "listen" port for N+, this also needs to be set in Nicotine+ Settings->Network->Listening Port too!
```

If you connect your container to a VPN that supports port forwarding, then you can skip the local portal forwarding and use the VPN forwarded port (which is how mine is setup). Otherwise, you need to forward the Nicotine+ listen port in your router.

For testing, I installed curl in the container and ran curl http://www.slsknet.org/porttest.php?port=xxxxx
Result:` Port: xxxxx/tcp open. Your router and Soulseek client is configured correctly.`
The only port I have exposed externally is the Nicotine+ LISTEN port, and it's only forwarded from my VPN, not in my router.

**Comment by mamema** [comment]
solved. The whole issue drove me crazy a few hours. You haven't this issue, no github entries about it, my router config is okay, so what is it?
It is a docker swarm issue. Doesn't work there for whatever reason.
As single local container it is working

**Comment by sirjmann92** [comment]
That's great! (or not? depending on your perspective)

Do you feel a documentation update is needed or are you good to close this?
